# [".local/bin/nu"]
# url = {{ gitHubLatestReleaseAssetURL "nushell/nushell" "nu-0.107.0-aarch64-unknown-linux-musl.tar.gz" | quote }}
# type = "archive-file"
# stripComponents = 1
# executable = true
# path = "nu"           # maybe change to nu
