alias emptytrash = sudo rm -rf ~/.local/share/Trash/files
alias clip = pbcopy # save contents of stdin to clipboard
alias cl = pbcopy
alias python = python3
alias n = nvim
alias v = nvim
alias l = lazygit
alias h = history
alias tf = terraform
alias k = kubectl
alias kgp = kubectl get po
alias d = docker
alias dc = docker-compose
