- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    # - include: tasks/ssh.yml
    - include_tasks: tasks/brew.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/node-setup.yml
