- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/brew.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/dots.yml
