[tools]
chezmoi = "latest"
neovim = "latest"
jq = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
rg = "latest"
node = "latest"
aws-cli = "latest"
kubectl = "latest"
kubeseal = "latest"
cosign = "latest"      # used to verify artifact signatures
kind = "latest"
python = "3.10"
age = "latest"
carapace = "latest"
cloudflared = "latest"
cowsay = "latest"
flux = "latest"
gh = "latest"
k9s = "latest"
k3d = "latest"
kubectx = "latest"
lazygit = "latest"
pnpm = "latest"
pulumi = "latest"
restish = "latest"
kustomize = "latest"
helm = "latest"
stern = "latest"
flux2 = "latest"
mkcert = "latest"
lazydocker = "latest"
container = "latest"
opentofu = "latest"
