[tools]
chezmoi = "latest"
neovim = "latest"
jq = "latest"
fd = "latest"
fzf = "latest"
rg = "latest"
node = "latest"
aws-cli = "latest"
kubectl = "latest"
kubeseal = "latest"
cosign = "latest"      # used to verify artifact signatures
kind = "latest"
terraform = "latest"
python = "3.10"
age = "latest"
carapace = "latest"
cloudflared = "latest"
cowsay = "latest"
flux = "latest"
gh = "latest"
