[tools]
chezmoi = "latest"
neovim = "latest"
jq = "latest"
fd = "latest"
rg = "latest"

node = "latest"
aws-cli = "latest"
kubectl = "latest"
kubeseal = "latest"
cosign = "latest"   # used to verify artifact signatures
