#!/usr/bin/env sh

# setup requires System Integrity Protection to be disabled:
#  - https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

# setup requires yabai injecting a scripting addition (sa) to control window layout & behavior:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
alias yc="yabai -m config"
alias yr="yabai -m rule"

# this can come in handy when scripting stuff
yabai -m space 1 --label "one"
yabai -m space 2 --label "two"
yabai -m space 3 --label "three"
yabai -m space 4 --label "four"
# ...

yc split_ratio 0.50 #
yc split_type auto  #
yc auto_balance off #

# padding & gaps
yc top_padding 4    # maximize screen real estate
yc bottom_padding 4 # maximize screen real estate
yc left_padding 4   # maximize screen real estate
yc right_padding 4  # maximize screen real estate
yc window_gap 4     # maximize screen real estate

yc layout bsp             # layout: binary space partitioning
yc mouse_modifier alt     # modifier for clicking and dragging with mouse
yc mouse_action1 move     # set modifier + left-click drag to move window
yc mouse_action2 resize   # set modifier + right-click drag to resize window
yc mouse_drop_action swap # when window is dropped in center of another window, swap them (e"

yc mouse_follows_focus on # center mouse on window with focus
# yc focus_follows_mouse on           # mouse follows focus
yc window_origin_display default   # center mouse on window with focus
yc window_placement second_child   # new window spawns to the right if vertical split, or bottom if horizontal split
yc window_zoom_persist on          #
yc window_shadow off               # disable window shadows
yc window_animation_duration 0.0   # all I care about is that speed though
yc window_animation_frame_rate 120 #
yc window_opacity_duration 0.0     #
yc active_window_opacity 1.0       #
yc normal_window_opacity 0.90      #
yc window_opacity off              #
yc insert_feedback_color 0xffd7

yr --add app="^Raycast" manage=off
yr --add app="^System Settings" manage=off
yr --add app="^Calculator$" manage=off
yr --add app="^Karabiner-Elements$" manage=off

borders active_color=0xff8E83B8 inactive_color=0xff494d64 width=4.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
